// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX2m_cUKt9YSmSPEXsEBA8T6AEN9GItiE',
    appId: '1:555210859419:web:fa755c05518c668b42f73e',
    messagingSenderId: '555210859419',
    projectId: 'habittrackerapp-815ac',
    authDomain: 'habittrackerapp-815ac.firebaseapp.com',
    storageBucket: 'habittrackerapp-815ac.firebasestorage.app',
    measurementId: 'G-RSE6X5B2CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFfQ3c6I2KtF9E92cxLm8T44ReISsEtp4',
    appId: '1:555210859419:android:c9407aaac11ba92442f73e',
    messagingSenderId: '555210859419',
    projectId: 'habittrackerapp-815ac',
    storageBucket: 'habittrackerapp-815ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVFef3YvKdLtSqBT-OoGr_-k3ZfF2EO7c',
    appId: '1:555210859419:ios:2aadd306806c92c842f73e',
    messagingSenderId: '555210859419',
    projectId: 'habittrackerapp-815ac',
    storageBucket: 'habittrackerapp-815ac.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVFef3YvKdLtSqBT-OoGr_-k3ZfF2EO7c',
    appId: '1:555210859419:ios:2aadd306806c92c842f73e',
    messagingSenderId: '555210859419',
    projectId: 'habittrackerapp-815ac',
    storageBucket: 'habittrackerapp-815ac.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX2m_cUKt9YSmSPEXsEBA8T6AEN9GItiE',
    appId: '1:555210859419:web:4ab38ea8b02d015742f73e',
    messagingSenderId: '555210859419',
    projectId: 'habittrackerapp-815ac',
    authDomain: 'habittrackerapp-815ac.firebaseapp.com',
    storageBucket: 'habittrackerapp-815ac.firebasestorage.app',
    measurementId: 'G-VFBBN5K138',
  );
}
